license="${mod_license}"
issueTrackerURL="https://github.com/EasterGhost/RailOptimization/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/railoptimization"
logoFile="assets/icon.png"
authors="Andrew Elizabeth / EasterGhost"
credits="Thanks to FxMorin for the original RailOptimization project."
description='''
Makes powered and activator rails turn on and off faster, especially in complex rail networks.
'''

[[mixins]]
config="railoptimization.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
