license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
modUrl="${mod_homepage}"
logoFile="${mod_icon}"
authors="${mod_authors}"
credits="${mod_contributor_credits}"
description='''${mod_description}'''

[modproperties.${mod_id}]
sources="${mod_sources}"
authorEmails="${mod_author_emails}"

[[mixins]]
config="railoptimization.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
